---
apiVersion: v1
kind: Service
metadata:
  name: redis-master
  labels:
    app: redis
spec:
  selector:
    app: redis
    role: master
  ports:
    - name: redis
      port: 6379
      targetPort: redis
