---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: grafana
  labels:
    app: grafana
rules:
  - apiGroups: ["extensions"]
    resources: ["podsecuritypolicies"]
    verbs: ["use"]
    resourceNames: [grafana]
