---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../Solution

configMapGenerator:
  - name: microgateway-config
    behavior: replace
    files:
      - config/config.yaml
