---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: microgateway-config
    files:
      - config/config.yaml

secretGenerator:
  - name: microgateway-secret
    files:
      - secret/passphrase
