---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

commonLabels:
  purpose: microgateway-tutorial

generatorOptions:
  disableNameSuffixHash: true
  labels:
    app: microgateway

configMapGenerator:
  - name: microgateway-config
    files:
      - config/config.yaml

secretGenerator:
  - name: microgateway-secret
    files:
      - secret/passphrase
