---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - serviceaccount.yaml
  - pvc.yaml
  - clusterrole.yaml
  - clusterrolebinding.yaml

commonLabels:
  purpose: microgateway-tutorial
  app: prometheus

configMapGenerator:
  - name: prometheus-server
    files:
      - config/alerting_rules.yml
      - config/alerts
      - config/prometheus.yml
      - config/recording_rules.yml
      - config/rules
