---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-server
  labels:
    app: prometheus
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "100M"
