---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-server
  labels:
    app: prometheus
spec:
  selector:
    app: prometheus
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 9090
