---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../.templates/ingress
  - ../../.templates/echoserver
  - ../../.templates/prometheus
  - artillery
  - echo-microgateway

patchesStrategicMerge:
  - patch-ingress.yaml

secretGenerator:
  - name: jwt-secret
    literals:
      - JWT_ENCRYPTION_PASSPHRASE=INH7mooVJcC8AcSq7Fp+NNGIbCPXvr2ls45b13om8w8=
      - JWT_SIGNATURE_PASSPHRASE=iEjj17tncge7qRjq2kXxXSV6emofSB+nQaw0Xece4HjLG1NbZH7IrRwAGxSMyHIaf0kQMvD3f0lrwTRhxdt13Q==
      - JWT_TOKEN=eyJjdHkiOiJKV1QiLCJlbmMiOiJBMjU2R0NNIiwiYWxnIjoiZGlyIn0..q_382QLa9P1N5xuv.STvykuZALmVkEDeRVssJ5J-W7gU-fbEUa3D-drurDji2CltNV31EW7mF7jnW-IGUw9dBvapHDtt-ADne8AhzpbDpmsCFDGY4pTbp-LFXpVtsLfhT1aWM8C245tB2CBT5Mr-wHzxfyRHwusZhgIljqE0qzQl6Ys-lxG2lYaXLc51ajBtq2C8TJoZ1WadhToNGoNx_begTDescWBerlrQxL-P2kMB-A_F_OpkUFkX3-S6dZOxtBTK-8EzZUvc_ButxskYjm24M3QneJ8J1NER0DORqxKh-MKdj3eTdYiQNUJ72N_POEQg_ubvDeSD4J9mF0XShE8Z5fWVhtPbzzw1VCSQbcp2gpIWfZuEnxkguwQwr1sV2.GcTNSVOFh5Coog2rY7dGXg
