---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

commonLabels:
  purpose: microgateway-tutorial

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: echoserver-nginx-config
    files:
      - config/nginx.conf
