---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

commonLabels:
  purpose: microgateway-tutorial
  app: openapi-petstore

generatorOptions:
  disableNameSuffixHash: true
