---
apiVersion: v1
kind: Service
metadata:
  name: openapi-petstore
  labels:
    app: openapi-petstore
spec:
  selector:
    app: openapi-petstore
  ports:
    - name: http
      port: 8080
      targetPort: http
