---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../../.templates/microgateway

namePrefix: prometheus-
commonLabels:
  backend: prometheus

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: microgateway-config
    behavior: replace
    files:
      - config/config.yaml
