---
apps:
  - virtual_host:
      name: echoserver
      hostname: echoserver.virtinc.local
    mappings:
      - name: echoserver
        backend:
          name: echoserver
          hosts:
            - name: echoserver
              protocol: http
              port: 8080
