---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - statefulset.yaml
  - service.yaml
  - serviceaccount.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: mariadb
    files:
      - config/my.cnf

secretGenerator:
  - name: mariadb
    literals:
      - mariadb-root-password=secretpassword
      - mariadb-password=TF9SkeLInU
