---
session:
  encryption_passphrase: /secret/config/passphrase

apps:
  - virtual_host:
      name: echoserver
      hostname: echoserver.virtinc.local
    mappings:
      - name: echoserver
        deny_rule_groups:
          - level: strict
        # extend the configuration according
        # to the instructions
