---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

commonLabels:
  purpose: microgateway-tutorial

configMapGenerator:
  - name: microgateway-config
    files:
      - config/config.yaml

secretGenerator:
  - name: microgateway-passphrase
    files:
      - secret/passphrase
  - name: microgateway-license
    files:
      - license=secret/microgateway.lic
