---
apiVersion: v1
kind: Service
metadata:
  name: microgateway
  labels:
    app: microgateway
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9102"
spec:
  selector:
    app: microgateway
  ports:
    - name: http
      port: 80
      targetPort: http
    - name: https
      port: 443
      targetPort: https
