---
apps:
  - virtual_host:
      name: prometheus
      hostname: prometheus.virtinc.local
    mappings:
      - name: prometheus
        entry_path:
          value: /prometheus/
        backend_path: /
        session_handling: ignore_session
        deny_rule_groups:
          - log_only: true
        backend:
          name: prometheus
          hosts:
            - protocol: http
              name: prometheus
              port: 9090
