---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../.templates/ingress
  - ../../.templates/microgateway
  - ../../.templates/virtinc
  - ../../.templates/wordpress
  - ../../.templates/redis
  - ../../.templates/iam

commonLabels:
  purpose: microgateway-tutorial

configMapGenerator:
  - name: microgateway-config
    behavior: replace
    files:
      - config/config.yaml
  - name: iam-microgateway-mapping-template-adminapp
    files:
      - iam-adminapp.xml=config/iam-adminapp-mgw2.0-mapping-template.xml
  - name: iam-microgateway-mapping-template-loginapp
    files:
      - iam-loginapp.xml=config/iam-loginapp-mgw2.0-mapping-template.xml
  - name: iam-microgateway-mapping-template-loginapp-rest-protected
    files:
      - iam-loginapp-rest-protected.xml=config/iam-loginapp-rest-protected-mgw2.0-mapping-template.xml
  - name: iam-microgateway-mapping-template-loginapp-rest-public
    files:
      - iam-loginapp-rest-public.xml=config/iam-loginapp-rest-public-mgw2.0-mapping-template.xml
  - name: iam-microgateway-openapi-login-rest
    files:
      - openapi-loginapp-rest.json=config/login-rest-openapi.json

patchesStrategicMerge:
  - patch-microgateway-deployment.yaml
