---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../.templates/ingress
  - ../../.templates/microgateway
  - ../../.templates/virtinc
  - ../../.templates/wordpress
  - ../../.templates/redis
  - ../../.templates/iam

commonLabels:
  purpose: microgateway-tutorial

configMapGenerator:
  - name: microgateway-config
    behavior: replace
    files:
      - microgateway/config/config.yaml
  - name: iam-microgateway-mapping-template-adminapp
    files:
      - iam-adminapp.xml=microgateway/config/iam-adminapp-mgw2.0-mapping-template.xml
  - name: iam-microgateway-mapping-template-loginapp
    files:
      - iam-loginapp.xml=microgateway/config/iam-loginapp-mgw2.0-mapping-template.xml
  - name: iam-microgateway-mapping-template-loginapp-rest-protected
    files:
      - iam-loginapp-rest-protected.xml=microgateway/config/iam-loginapp-rest-protected-mgw2.0-mapping-template.xml
  - name: iam-microgateway-mapping-template-loginapp-rest-public
    files:
      - iam-loginapp-rest-public.xml=microgateway/config/iam-loginapp-rest-public-mgw2.0-mapping-template.xml
  - name: iam-microgateway-openapi-login-rest
    files:
      - openapi-loginapp-rest.json=microgateway/config/login-rest-openapi.json
  - name: iam-config
    files:
      - iam/config/medusa-configuration.xml
  - name: iam-properties
    files:
      - iam/config/users.properties
      - iam/config/admins.properties

patchesStrategicMerge:
  - patch-microgateway-deployment.yaml
  - patch-iam-statefulset.yaml
