---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../../.templates/artillery

configMapGenerator:
  - name: artillery-config
    behavior: replace
    files:
      - config/artillery.yaml

patchesStrategicMerge:
  - patch-deployment.yaml
