---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: artillery
spec:
  template:
    spec:
      containers:
        - name: artillery
          env:
            - name: JWT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_TOKEN